[package]
name = "the_simplest_webgpu_app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = { version = "0.29", features = ["rwh_05"] }
wgpu = "0.19"
pollster = "0.3"
bytemuck = "1.14"